services:
  # Python FastAPI Model Service
  - type: web
    name: translation-model-service
    env: python
    plan: starter
    buildCommand: pip install -r backend/models/requirements.txt
    startCommand: cd backend/models && uvicorn model_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8008
      - key: HOST
        value: 0.0.0.0
      - key: MODEL_REPOS
        value: ShreyaSinghBhrigu/mariammt-enfr
      - key: MODEL_PAIRS
        value: en-fr
      - key: HUGGING_FACE_HUB_TOKEN
        sync: false
      - key: MAX_TEXT_LENGTH
        value: 512
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: TEMP_DIR
        value: /tmp

  # Node.js Backend API Gateway
  - type: web
    name: translation-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_HOST
        fromService:
          type: web
          name: translation-frontend
          property: host
      - key: FRONTEND_PORT
        fromService:
          type: web
          name: translation-frontend
          property: port
      - key: PYTHON_API_HOST
        fromService:
          type: web
          name: translation-model-service
          property: host
      - key: PYTHON_API_PORT
        fromService:
          type: web
          name: translation-model-service
          property: port
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: LOG_LEVEL
        value: info

  # React Frontend
  - type: web
    name: translation-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_HOST
        fromService:
          type: web
          name: translation-backend
          property: host
      - key: REACT_APP_API_PORT
        fromService:
          type: web
          name: translation-backend
          property: port
      - key: NODE_ENV
        value: production
      - key: GENERATE_SOURCEMAP
        value: false
